### ISSUE TITLE
question: possible to include bin extras script in pre-built downloads as well?

### ISSUE THREAD

**Issue by liamstask** [jsnyder/arm-eabi-toolchain#12]
Hi! Thanks for your work providing these scripts/builds.

Since it's so convenient to use the pre-built binaries, I was wondering if it would be possible to create a separate script (or even just a copy of the Makefile if that works?) to grab the CodeSourcery extras in the same way as they are for a source build, using the `make install-bin-extra` command.

My motivation is that I was just getting my environment set up to run under qemu, and there are a few extra libs and linker scripts in there that are required (as far as I know) to get going.

Thanks!

**Comment by jsnyder** [comment]
I'd have to take a look at the license again in order to figure out whether I can redistribute the binary files in my own downloads (scripting it was easiest, least ambiguous); however, you should be able to use the makefile to do "install-bin-extras", provided you either use the same default install location I do $(HOME)/arm-cs-tools/ or you use the updated ability to override the PREFIX as should now be mentioned in the README.

ALTERNATIVE:
Another, even simpler alternative if you're not comfortable with any of that is to basically just download the bin url for the release the Makefile is working with (2010.09), unzip it and copy the contents in that archives "arm-none-eabi" to the pre-compiled version you're working with.

Do let me know if you try the Makefile method and something doesn't work though I only did some quick checking on it to make sure it seemed to be still working :-)

**Comment by liamstask** [comment]
The Makefile seems to work for me - being able to change the prefix did the trick. Thanks again!
