### ISSUE TITLE
installation directory

### ISSUE THREAD

**Issue by micromouseonline** [jsnyder/arm-eabi-toolchain#9]
Any particular reason why you build this to the users home folder by default? It appears to me that, if I built to a folder like /usr/loca/arm-tools or some such, I could copy the result to my other machines without a lengthy build.

**Comment by jsnyder** [comment]
I believe you should be able to move the built binaries to other locations if you want, though I haven't tried putting them elsewhere.  You can also change the prefix during build time, although as it is currently set up it might be simplest to give yourself user permissions in the destination directory.

I'll work on making it easier to do something like make PREFIX=/usr/local/arm-tools in the future, I think since this was requested either on this toolchain or on the avr32 toolchain I maintain.

**Comment by micromouseonline** [comment]
Thank you.

I had believed that the prefix needed to be the same as the installation location but I am not sure now.

Today, I have tried  a lot but failed to make the installation work on OS X Lion.

Peter Harrison

**Comment by jsnyder** [comment]
> I had believed that the prefix needed to be the same as the installation location but I am not sure now

I don't believe so, however I could be wrong.  I do have binaries that are on the site that others have downloaded and I suspect have had success with that were definitely built for my home directory.  I've presumed that since I've not had complaints about these that they've worked in other home directories which have different paths.

> Today, I have tried  a lot but failed to make the installation work on OS X Lion.

Do you mean that a build failed from scratch or something else?  I have to confess that although I've got Lion running, I haven't tried a build yet.  If you were using XCode 4 before you will definitely need 4.1 since it moves 4.0.x out of the way. I'll give a build a try today and see how things go.

**Comment by micromouseonline** [comment]
I upgraded everything, including xCode. Downloaded your stuff. Cleared out the macports and followed the instructions. Three times.

It chugged away for ages and then gave me an error 2 failure with about 37 yards of preceding output as a clue as to why. If I knew that I might have tried to fix it :)

Peter Harrison

**Comment by jsnyder** [comment]
Looks like this might be a common issue with llvm-gcc that has potentially been fixed in a later version than what is shipping.  I've created a separate [issue](https://github.com/jsnyder/arm-eabi-toolchain/issues/10).

**Comment by micromouseonline** [comment]
Thank you for looking at it. I wish I could help.

Peter Harrison

**Comment by jsnyder** [comment]
I believe I've got a workaround for now that should work that involves using clang to build everything except for GCC.  I haven't tried it from a completely clean start, but what I now have on the readme file, should get everything built.  The only complication was GDB which has something that clang (rightfully) blew up on.
